### PR TITLE
Add integration tests for scoped packages and semver ranges

### PR DESCRIPTION
**Pull request by rstacruz**
Just covering more bases here.

### CODE REVIEW

**Comment by alexanderGugel** [comment]
Rebase please.

**Comment by rstacruz** [comment]
rebased

**Comment by rstacruz** [comment]
and apparently it breaks now... haha.

**Comment by alexanderGugel** [comment]
Want to fix it or should I close?

**Comment by rstacruz** [comment]
sorry, i'm not sure where to start!

**Comment by alexanderGugel** [comment]
Thanks anyways :smile:

**Pull request closed without merging**
