### PR TITLE
Move to yargs. Autogenerates usage and fixes #12

### LINKED ISSUE #12: --save-dev also copy "dependencies" into "devDependencies"
for [ied](https://github.com/alexanderGugel/ied) repo it self:

```
16:57:34 nos:~/Documents/Projects/ied 9 (master u=)
~> ied install --save-dev debug
16:57:51 nos:~/Documents/Projects/ied 9 (master * u=)
~> gd
diff --git a/package.json b/package.json
index fa0aa17..507a5b7 100644
--- a/package.json
+++ b/package.json
@@ -19,11 +19,22 @@
     "tar-fs": "^1.8.1"
   },
   "devDependencies": {
-    "mocha": "^2.3.3",
+    "mocha": "^2.3.4",
     "mock-fs": "^3.4.0",
-    "mockmock": "0.0.5",
+    "mockmock": "^0.0.5",
     "proxyquire": "^1.7.3",
-    "standard": "^5.3.1"
+    "standard": "^5.3.1",
+    "archy": "^1.0.0",
+    "async": "^1.5.0",
+    "easy-table": "^1.0.0",
+    "gunzip-maybe": "^1.2.1",
+    "init-package-json": "^1.9.1",
+    "minimist": "^1.2.0",
+    "mkdirp": "^0.5.1",
+    "node-uuid": "^1.4.7",
+    "object-assign": "^3.0.0",
+    "semver": "^5.0.3",
+    "tar-fs": "^1.8.1"
   },
   "scripts": {
     "test": "mocha && standard",
@@ -44,4 +55,4 @@
     "example": "example",
     "test": "test"
   }
-}
+}
\ No newline at end of file
```

### PR DESCRIPTION
**Pull request by STRML**
This also adds the `help` command:

```bash
$ ied help
ied is a package manager for Node.

Usage:

ied <command> [arguments]

Commands:
  install [package]  Fetch all packages or an individual package
  run <command>      Run a package.json script
  test               Run the test script specified in the package.json
  shell              Enter a sub-shell with an augmented PATH
  ping               Check if the registry is up
  ls                 Print the dependency graph
  config             Print the current config
  init               Initialize a new package
  link [package]     Link the current package or into it
  unlink [package]   Unlink the current package or from it
  help [command]     View help on an individual command

Options:
  --version   Show version number                                              [boolean]
  -h, --help  Show usage information                                           [boolean]

README:  https://github.com/alexanderGugel/ied
ISSUES:  https://github.com/alexanderGugel/ied/issues
```

```bash
$ ied help install
ied install [package]

Options:
  --version       Show version number                                                                 [boolean]
  -h, --help      Show usage information                                                              [boolean]
  -S, --save      Update package.json dependencies                                                    [boolean]
  -D, --save-dev  Update package.json devDependencies                                                 [boolean]
  -o, --only      Install a subset of dependencies
  -r, --registry  Use a custom registry                                 [default: "https://registry.npmjs.org"]

Examples:
  ied install
  ied install <pkg>
  ied install <pkg>@<version>
  ied install <pkg>@<version range>
  ied install --only=production                                  Install dependencies only, not devDependencies
  ied install --registry="https://npm.mycorp.com" <pkg>              Install a package from your local registry
```

### CODE REVIEW

**Comment by STRML** [comment]
Force-pushed a lint fix

**Comment by alexanderGugel** [comment]
Not a big fan of dynamically generated docs TBH. Last time I tried yargs it had a massive dependency graph and `require`d in like a hundred files. Will try this out...

**Comment by STRML** [comment]
This is going to give us a lot of flexibility in arg parsing, and ensures the docs always follow the code. It also fixes #12 because the existing argument parser has an issue with flag positioning.

If, in the future, something it autogenerates is no good, we can have it display a static file as part/all of the output.

It seems the dep tree is under control:

```
└─┬ yargs@4.4.0
  ├── cliui@3.1.2
  ├─┬ lodash.assign@4.0.7
  │ ├── lodash.keys@4.0.6
  │ └── lodash.rest@4.0.2
  ├─┬ pkg-conf@1.1.2
  │ ├── object-assign@4.0.1
  │ └── symbol@0.2.1
  ├── require-main-filename@1.0.1
  ├── window-size@0.2.0
  └─┬ yargs-parser@2.2.0
    ├── camelcase@2.1.1
    └─┬ lodash.assign@4.0.7
      └── lodash.keys@4.0.6
```

**Comment by alexanderGugel** [comment]
@STRML Ok, you convinced me :smile: If you submit this against `rebirth` (the next version of ied), I will merge. This might give you a bunch of merge conflicts TBH, but should be fairly easy to resolve. Let me know if I can help!

**Comment by alexanderGugel** [comment]
Closed for #110

**Pull request closed without merging**
