### PR TITLE
Support dependencies from arbitrary tarballs

### PR DESCRIPTION
**Pull request by just-boris**
Hello! I implemented really missing feature for me. Now it is possible to install dependencies like this:
```json
{
 "gulp": "https://github.com/gulpjs/gulp/archive/4.0.tar.gz",
}
```
Because newest version hasn't released yet, it is not available from NPM and a lot of users pull it directly from Github. So it can be a quite common use-case.

Here is a short list of my changes

1. Use [npm-package-arg](https://github.com/npm/npm-package-arg). NPM itself uses this package to parse dependencies and choose a way how to fetch them. 
2. `resolve.js` file redirects request to a specific resolver. There are two resolvers implemented: 
    * NPM registry - ask registry for package and returns link to tarball of satisfying version
    * Tarball - just returns link to tarball
    * Github (not implemented) - returns an error, that GitHub is not supported yet.
3. Package directory now is a `sha1(name@version')`. We can't get shasum for arbitrary tarballs, but hash from name and version seems like a good alternative to keep package directory unique.
4. Use [got](https://github.com/sindresorhus/got) instead of native `http`. Got can handle redirects and retry on request errors. Redirect handling is necessary thing because Github responds with a redirect when you follow the download link from UI. Also, I used [nock](https://github.com/pgte/nock) for http mocking because I think that it is better than write our own mocks for `got`.

If you want any more questions I will be happy to answer.

### CODE REVIEW

**Comment by just-boris** [comment]
My second build in a row on AppVeyor is failing. I think that is issue with its setup.

**Comment by alexanderGugel** [comment]
Wow! Looks awesome!

I will take some time this week to review and merge this.

**Comment by alexanderGugel** [comment]
BOOM! Sick awesome. I'm going to remove appveyor for now. It's kind of annoying.

**Comment by shouze** [comment]
:+1: I wanted to test ied on one project but I need [github resolver](https://github.com/just-boris/ied/blob/2b32b2ad6468a3631329ee999c32ccaf6b958df8/lib/resolvers/github.js) to be implemented.

**Comment by just-boris** [comment]
You can work around it using GitHub feature to download repositories as tarball, for example, https://github.com/alexanderGugel/ied/archive/master.zip

I am going to implement it eventually, but I can't say any estimate

**Comment by shouze** [comment]
@just-boris thank you for the tip ;) it works but ied don't support yes binary dependencies build, it's the next stop to me.

**Pull request merged**
