### PR TITLE
added shortcut for 'shell': ied -s

### PR DESCRIPTION
**Pull request by davyengone**
I guess this doesn't conflict with the save option so I added a shortcut for running 'shell' option on the command line. 

Let's me know what you think!

### CODE REVIEW

**Comment by FarhadG** [comment]
Wow, to have @davyengone's code merged in... :)

**Comment by davyengone** [comment]
Well @FarhadG , that's not much of a contribution :)  Just to let's him know that I'm watching this repo very closely :)

**Comment by alexanderGugel** [comment]
Not too sure about that. While it doesn't conflict with the save flag, it's probably quite confusing to have the same flag do two different things in a different context.

**Comment by alexanderGugel** [comment]
`sh` is fine for now. Thanks anyways!

**Comment by davyengone** [comment]
oh sorry I missed this one! Indeed, you're right ```sh``` makes more sense

**Pull request closed without merging**
