### PR TITLE
Fix build for specific npm-related edge cases

### PR DESCRIPTION
**Pull request by mgcrea**
##### Checklist

- [X] tests and code linting passes
- [X] a test is included
- [X] the commit message follows commit guidelines

##### Affected core subsystem(s)

Build

##### Description of change

Added support for `dtrace-provider@0.6.0` build.

### CODE REVIEW

**Comment by mgcrea** [comment]
I've added a commit to this PR that fixed many builds when trying on a complex package.json from a modern react app. Basically all builds are now run serially. That prevents race conditions that would make the builds fail most of the time when several builds where run in parallel.

**Comment by alexanderGugel** [comment]
Uh, that's interesting.

**Comment by mgcrea** [comment]
@alexanderGugel I don't think the order matters, I encountered mostly `file missing` errors that would not  happen when I installed+build packages one by one. I guess `node-gyp` does not like being run in parallel.

**Comment by mgcrea** [comment]
By the way, I think we should build by default (and maybe add an option to skip builds), having non working setups after an `ied i` feels a bit clunky.

**Pull request merged**
