### PR TITLE
First stab at renaming this project from `ied` to `nom`

### PR DESCRIPTION
**Pull request by mstade**
Following the discussion in alexanderGugel/ied#29 this is a first
effort to rename the project to `nom`. This would affect other
things than just this repository, such as the Travis CI set up
and surely other things as well. These changes assume those other
tools and locations have or will be changed as well.

### CODE REVIEW

**Comment by mstade** [comment]
Hi @alexanderGugel – very cool project!

I really like the ideas you've put forward here, and the effort you've put in to this repository. Thank you very much for showing there can be viable npm alternatives!

I'm hoping I can contribute more to the success of this project at some point, but I saw #29 and figured it's something I'd be able to spend some time on and hopefully let you focus on more meaningful stuff. Right now, the node 0.10 build looks like it's failing, but the 4.x build passes. The tests do *not* pass locally unfortunately, for reasons that escape me at the moment. I'll try to sort all of these things out, so you can hopefully just merge this whenever it's convenient (and indeed, presuming you'll want to go for `nom` at all.)

**Comment by rstacruz** [comment]
heheh, `nom` i guess can stand for `no`de `m`odulist

**Comment by rstacruz** [comment]
might need a rebase.

**Comment by mstade** [comment]
Most definitely needs a rebase, but not really worthwhile until @alexanderGugel puts in a couple of cents.

**Comment by alexanderGugel** [comment]
Thanks, but I'm not going to rename this project anytime soon.

**Comment by rstacruz** [comment]
why not?

**Pull request closed without merging**
